"""initial

Revision ID: 985ec819b090
Revises:
Create Date: 2025-05-05 20:50:42.276771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "985ec819b090"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Pets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("breed", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("age", sa.String(), nullable=True),
        sa.Column("sex", sa.String(), nullable=True),
        sa.Column("vid", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Pets")
    # ### end Alembic commands ###
