"""ssss

Revision ID: 662d6ae28f28
Revises: 79e9aba8b65c
Create Date: 2025-05-06 02:01:00.563151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "662d6ae28f28"
down_revision: Union[str, None] = "79e9aba8b65c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("license_number", sa.String(length=50), nullable=False),
        sa.Column("established_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("license_number"),
    )
    op.create_index(op.f("ix_clinics_name"), "clinics", ["name"], unique=False)
    op.create_table(
        "doctors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("specialization", sa.String(length=100), nullable=False),
        sa.Column("license_number", sa.String(length=50), nullable=False),
        sa.Column("clinic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("license_number"),
    )
    op.create_index(
        op.f("ix_doctors_first_name"), "doctors", ["first_name"], unique=False
    )
    op.create_index(
        op.f("ix_doctors_last_name"), "doctors", ["last_name"], unique=False
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("min_stock", sa.Integer(), nullable=False),
        sa.Column("last_ordered", sa.DateTime(), nullable=False),
        sa.Column("clinic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "doctor_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Date(), nullable=False),
        sa.Column("end_time", sa.Date(), nullable=False),
        sa.Column("clinic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("doctor_schedules")
    op.drop_table("medications")
    op.drop_index(op.f("ix_doctors_last_name"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_first_name"), table_name="doctors")
    op.drop_table("doctors")
    op.drop_index(op.f("ix_clinics_name"), table_name="clinics")
    op.drop_table("clinics")
    # ### end Alembic commands ###
