"""add med card

Revision ID: 2febe378aa59
Revises: 985ec819b090
Create Date: 2025-05-05 20:57:52.074612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2febe378aa59"
down_revision: Union[str, None] = "985ec819b090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "MedCards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pet_id", sa.Integer(), nullable=False),
        sa.Column("vactination", sa.String(), nullable=True),
        sa.Column("alergic", sa.String(), nullable=True),
        sa.Column("chronic_diseases", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pet_id"],
            ["Pets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("MedCards")
    # ### end Alembic commands ###
