"""add roles

Revision ID: 1f417ce7b3fe
Revises: 1ccbdc94b238
Create Date: 2025-05-06 07:33:45.504013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f417ce7b3fe"
down_revision: Union[str, None] = "1ccbdc94b238"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Создаем тип перечисления в базе данных
    op.execute('CREATE TYPE userrole AS ENUM (\'ADMIN\', \'USER\', \'DEBUG\')')

    # Добавляем столбец role без ограничения NOT NULL
    op.add_column(
        "users",
        sa.Column(
            "role", sa.Enum("ADMIN", "USER", "DEBUG", name="userrole"), nullable=True
        ),
    )

    # Устанавливаем значение по умолчанию для всех существующих записей
    op.execute('UPDATE users SET role = \'USER\'')

    # Добавляем ограничение NOT NULL
    op.alter_column("users", "role", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
