"""change booking

Revision ID: 0dd3c4040226
Revises: 263801b704ec
Create Date: 2025-05-05 22:30:42.541699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dd3c4040226"
down_revision: Union[str, None] = "263801b704ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "doctor_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("doctor_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
