"""change bookings

Revision ID: 263801b704ec
Revises: fdcdf7a17be8
Create Date: 2025-05-05 22:14:18.178063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "263801b704ec"
down_revision: Union[str, None] = "fdcdf7a17be8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("tg_username", sa.String(), nullable=True))
    op.drop_column("bookings", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("bookings", "tg_username")
    # ### end Alembic commands ###
