"""change pets

Revision ID: 72da6445623a
Revises: 1f417ce7b3fe
Create Date: 2025-05-06 08:59:24.301474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72da6445623a"
down_revision: Union[str, None] = "1f417ce7b3fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Pets", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "Pets", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Pets", type_="foreignkey")
    op.drop_column("Pets", "user_id")
    # ### end Alembic commands ###
