spring.application.name=appointment
server.port=8081
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.url=jdbc:postgresql://localhost:5432/zakazi
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=663467
#spring.jpa.show-sql=true
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.drop-first=true

spring.redis.host=localhost
spring.redis.port=6379

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/firstrealm

bot.name=Cool12222Bot
bot.token=7688795571:AAEIAq62Ceif_n-3GQTFpis7xEqKoqzi7G4
bot.path=/webhook
bot.webhook.url=https://z7py72-212-164-39-54.ru.tuna.am